# Generated by Django 6.0.6 on 2026-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0003_rename_gols_against_standing_goals_against_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='modality',
            field=models.CharField(choices=[('FOOTBALL', 'Futebol'), ('BASKETBALL', 'Basquete'), ('VOLLEYBALL', 'Vôlei'), ('SOCIETY', 'Society'), ('FUTSAL', 'Futsal')], max_length=20),
        ),
    ]
