# Generated by Django 6.0.6 on 2026-06-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchevent'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
